In [23]:
import sys
import pandas as pd
import numpy as np
import torch

from transformers import (
    EarlyStoppingCallback,
    PatchTSTConfig,
    PatchTSTForPrediction,
    Trainer,
    TrainingArguments    
)

import optuna
from optuna.samplers import TPESampler

# Adiciona o diretório src ao path de forma mais robusta
sys.path.insert(0, '../')

from src import RepositorioDados
from src import evaluate_and_visualize, compute_metrics

# Detecta o dispositivo e a precisão usada nas operações
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.bfloat16 if (device.type == "cuda" and torch.cuda.is_bf16_supported()) else torch.float32
print(f"Device: {device} | Precision: {dtype}")

# Seed para resultados reproduzíveis
RANDOM_STATE = 42
torch.manual_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

Device: cpu | Precision: torch.float32

In [24]:
# 1. Features
LAGS = [3, 5, 7, 9]  # Lags de 1 a 5
USE_MEAN_FEATURES = [True, False]

# 2. Janelas temporais
CONTEXT_LENGTHS = [256, 275, 300, 325, 350]
FORECAST_HORIZONS = [1]  # Manter fixo por enquanto

# 3. Hiperparâmetros do modelo
MODEL_PARAMS = {
    'd_model':  [64, 128],
    'num_attention_heads': [16],
    'num_hidden_layers': [2, 5],
    'ffn_dim': [128, 256],
    'dropout': [0.05, 0.1],
    'patch_length': [8],
}

# 4. Hiperparâmetros de treinamento
TRAINING_PARAMS = {
    'learning_rate': [5e-4],
    'batch_size': [32, 64],
}

# Configurações fixas
FIXED_PARAMS = {
    'timestamp_col': 'timestamp',
    'target_col': ['Vol'],
    'id_columns': [],
    'forecast_horizon': 1,
    'epochs': 10,  # Reduzido para grid search
    'early_stopping_patience': 5,
    'num_workers': 0,
    'train_frac': 0.7,
    'valid_frac': 0.1,
}

print("Espaços de busca definidos")
print(f"Total de combinações de features: {len(LAGS) * len(USE_MEAN_FEATURES)}")
print(f"Total de combinações de context_length: {len(CONTEXT_LENGTHS)}")
print(f"Total de combinações de modelo: {np.prod([len(v) for v in MODEL_PARAMS.values()])}")
print(f"Total de combinações de treinamento: {np.prod([len(v) for v in TRAINING_PARAMS.values()])}")
total = len(LAGS) * len(USE_MEAN_FEATURES) * len(CONTEXT_LENGTHS) * np.prod([len(v) for v in MODEL_PARAMS.values()]) * np.prod([len(v) for v in TRAINING_PARAMS.values()])
print(f"\n🔍 Total de experimentos: {int(total)}")

Espaços de busca definidos
Total de combinações de features: 8
Total de combinações de context_length: 5
Total de combinações de modelo: 16
Total de combinações de treinamento: 2

🔍 Total de experimentos: 1280

In [25]:
import pandas as pd

pd.set_option('display.max_columns', None)

results_opt = pd.read_csv("./optuna_results_v2.csv")

results_opt.sort_values('eval_RMSE').head()

,status,error,experiment_id,lags,num_features,use_mean_features,context_length,forecast_horizon,d_model,num_attention_heads,num_hidden_layers,ffn_dim,dropout,patch_length,learning_rate,batch_size,train_loss,eval_loss,eval_MSE,eval_MAE,eval_RMSE,eval_MAPE,epochs_trained
17,success,NaN,17.0,3.0,3.0,False,300.0,1.0,128.0,16.0,2.0,256.0,0.05,8.0,0.0005,32.0,0.583428,0.024682,0.024682,0.087462,0.157106,47.291943,0.0
15,success,NaN,15.0,3.0,3.0,False,300.0,1.0,128.0,16.0,2.0,256.0,0.05,8.0,0.0005,32.0,0.583428,0.024682,0.024682,0.087462,0.157106,47.291943,0.0
14,success,NaN,14.0,3.0,3.0,False,300.0,1.0,128.0,16.0,2.0,256.0,0.05,8.0,0.0005,32.0,0.583428,0.024682,0.024682,0.087462,0.157106,47.291943,0.0
33,success,NaN,33.0,3.0,3.0,False,300.0,1.0,128.0,16.0,2.0,256.0,0.05,8.0,0.0005,32.0,0.583428,0.024682,0.024682,0.087462,0.157106,47.291943,0.0
13,success,NaN,13.0,3.0,3.0,False,300.0,1.0,128.0,16.0,2.0,128.0,0.10,8.0,0.0005,32.0,0.587165,0.025103,0.025103,0.088295,0.158439,48.621649,0.0

In [26]:
def run_experiment(
    repo,
    context_length,
    forecast_horizon,
    d_model,
    num_attention_heads,
    num_hidden_layers,
    ffn_dim,
    dropout,
    patch_length,
    learning_rate,
    batch_size,
    experiment_id,
    use_mean_features,
    lags
    ,config_params=FIXED_PARAMS,
):
    """
    Executa um experimento completo com os parâmetros fornecidos.
    Retorna um dicionário com os resultados.
    """
    lags_count = int(lags) if isinstance(lags, int) else len(lags)
    
    print(f"\n{'='*80}")
    print(f"🧪 EXPERIMENTO {experiment_id}")
    print(f"{'='*80}")
    print(f"Context Length: {context_length} | Horizon: {forecast_horizon}")
    print(f"d_model: {d_model}, heads: {num_attention_heads}, layers: {num_hidden_layers}")
    print(f"LR: {learning_rate}, Batch: {batch_size}, Patch: {patch_length}")
    print(f"{'='*80}\n")
    
    try:
        # 1. Preparar dados
        tsp, train_ds, valid_ds, test_ds, _, _, _ = repo.executar(
            timestamp_col=config_params['timestamp_col'],
            train_frac=config_params['train_frac'],
            valid_frac=config_params['valid_frac'],
            context_length=context_length,
            target_col=config_params['target_col'],
            id_columns=config_params['id_columns'],
            forecast_horizon=forecast_horizon,
            use_mean_features=use_mean_features,
            lags=lags)
        
        # 2. Configurar modelo
        config = PatchTSTConfig(
            context_length=context_length,
            patch_length=patch_length,
            num_input_channels=len(config_params['target_col']),
            patch_stride=patch_length,
            prediction_length=forecast_horizon,
            d_model=d_model,
            num_attention_heads=num_attention_heads,
            num_hidden_layers=num_hidden_layers,
            ffn_dim=ffn_dim,
            dropout=dropout,
            head_dropout=dropout,
            pooling_type=None,
            channel_attention=True, # Ativação da atenção entre canais
            loss='mse',
            pre_norm=True,
            norm_type='batchnorm',
        )
        
        model = PatchTSTForPrediction(config=config).to(device).to(dtype)
        
        # 3. Configurar treinamento
        train_args = TrainingArguments(
            output_dir="./grid_search_temp",
            overwrite_output_dir=True,
            learning_rate=learning_rate,
            num_train_epochs=config_params['epochs'],
            do_eval=True,
            eval_strategy="epoch",
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            dataloader_num_workers=config_params['num_workers'],
            save_strategy="no",
            logging_strategy="epoch",
            logging_dir=None,
            load_best_model_at_end=False,
            metric_for_best_model="eval_loss",
            greater_is_better=False,
            label_names=["future_values"],
            report_to="none",
            fp16=(dtype == torch.float16),
            bf16=(dtype == torch.bfloat16),
        )
        
        early_stopping = EarlyStoppingCallback(
            early_stopping_patience=config_params['early_stopping_patience'],
            early_stopping_threshold=0.001
        )
        
        trainer = Trainer(
            model=model,
            args=train_args,
            train_dataset=train_ds,
            eval_dataset=valid_ds,
            compute_metrics=compute_metrics,
            callbacks=[early_stopping]
        )
        
        # 4. Treinar
        train_result = trainer.train()
        
        # 5. Avaliar no conjunto de validação
        eval_result = trainer.evaluate()
        
        # 6. Coletar métricas
        result = {
            'experiment_id': experiment_id,
            'lags': lags,
            'num_features': lags_count + (1 if use_mean_features else 0),
            'use_mean_features': use_mean_features,
            'context_length': context_length,
            'forecast_horizon': forecast_horizon,
            'd_model': d_model,
            'num_attention_heads': num_attention_heads,
            'num_hidden_layers': num_hidden_layers,
            'ffn_dim': ffn_dim,
            'dropout': dropout,
            'patch_length': patch_length,
            'learning_rate': learning_rate,
            'batch_size': batch_size,
            'train_loss': train_result.training_loss,
            'eval_loss': eval_result['eval_loss'],
            'eval_MSE': eval_result.get('eval_MSE', None),
            'eval_MAE': eval_result.get('eval_MAE', None),
            'eval_RMSE': eval_result.get('eval_RMSE', None),
            'eval_MAPE': eval_result.get('eval_MAPE', None),
            'epochs_trained': train_result.global_step // len(train_ds) * batch_size,
            'status': 'success'
        }
        
        print(f"✅ Experimento {experiment_id} concluído!")
        print(f"   Val Loss: {eval_result['eval_loss']:.6f} | RMSE: {result['eval_RMSE']:.6f}")
        
        # Limpar memória
        del model, trainer, train_ds, valid_ds, test_ds, tsp
        torch.cuda.empty_cache() if torch.cuda.is_available() else None
        
        return result
        
    except Exception as e:
        print(f"❌ Erro no experimento {experiment_id}: {str(e)}")
        return {
            'experiment_id': experiment_id,
            'lags': lags,
            'num_features': lags_count + (1 if use_mean_features else 0),
            'use_mean_features': use_mean_features,
            'context_length': context_length,
            'forecast_horizon': forecast_horizon,
            'd_model': d_model,
            'learning_rate': learning_rate,
            'batch_size': batch_size,
            'status': 'failed',
            'error': str(e)
        }

print("✓ Função run_experiment definida (com modo rápido)")

✓ Função run_experiment definida (com modo rápido)

In [27]:
def optuna_objective(trial):
    """Função objetivo para Optuna. Retorna a métrica a ser MINIMIZADA."""

    lags = trial.suggest_categorical('lags', LAGS)
    use_mean_features = trial.suggest_categorical('use_mean_features', USE_MEAN_FEATURES)

    context_length = trial.suggest_categorical('context_length', CONTEXT_LENGTHS)
    forecast_horizon = trial.suggest_categorical('forecast_horizon', FORECAST_HORIZONS)

    d_model = trial.suggest_categorical('d_model', MODEL_PARAMS['d_model'])
    num_attention_heads = trial.suggest_categorical('num_attention_heads', MODEL_PARAMS['num_attention_heads'])
    num_hidden_layers = trial.suggest_categorical('num_hidden_layers', MODEL_PARAMS['num_hidden_layers'])
    ffn_dim = trial.suggest_categorical('ffn_dim', MODEL_PARAMS['ffn_dim'])
    dropout = trial.suggest_categorical('dropout', MODEL_PARAMS['dropout'])
    patch_length = trial.suggest_categorical('patch_length', MODEL_PARAMS['patch_length'])

    learning_rate = trial.suggest_categorical('learning_rate', TRAINING_PARAMS['learning_rate'])
    batch_size = trial.suggest_categorical('batch_size', TRAINING_PARAMS['batch_size'])

    # Filtrar combinações inválidas (heads devem dividir d_model)
    if d_model % num_attention_heads != 0:
        trial.set_user_attr('full_result', {'status': 'failed', 'error': 'heads_not_divisible'})
        return float('inf')

    # Executar experimento
    result = run_experiment(
        repo=RepositorioDados(),
        context_length=context_length,
        forecast_horizon=forecast_horizon,
        d_model=d_model,
        num_attention_heads=num_attention_heads,
        num_hidden_layers=num_hidden_layers,
        ffn_dim=ffn_dim,
        dropout=dropout,
        patch_length=patch_length,
        learning_rate=learning_rate,
        batch_size=batch_size,
        experiment_id=trial.number,
        use_mean_features=use_mean_features,
        lags=lags
    )

    # Salvar resultado completo
    trial.set_user_attr('full_result', result)

    if result['status'] == 'failed':
        return float('inf')

    return result['eval_RMSE']  # ou 'eval_loss'

In [28]:
study = optuna.create_study(
    direction='minimize',  # Minimizar RMSE
    sampler=TPESampler(seed=RANDOM_STATE),
    study_name='patchtst_optimization'
)

[I 2026-02-17 11:28:56,830] A new study created in memory with name: patchtst_optimization

In [29]:
from datetime import datetime
start_time = datetime.now()

# Executar otimização
study.optimize(
    optuna_objective,
    n_trials=100,  # ⚡ REDUZIDO: 200 → 50
    show_progress_bar=True,
    callbacks=[
        lambda study, trial: study.trials_dataframe().to_csv(
            'optuna_results_partial.csv', index=False
        ) if trial.number % 5 == 0 else None
    ],
    gc_after_trial=True  # ⚡ NOVO: Libera memória após cada trial
)

end_time = datetime.now()
duration = end_time - start_time

print(f"\n{'='*80}")
print(f"✅ Busca Optuna concluída!")
print(f"⏱️ Tempo total: {duration}")
print(f"🏆 Melhor RMSE: {study.best_value:.6f}")
print(f"{'='*80}\n")

# Extrair resultados
results = [trial.user_attrs.get('full_result') for trial in study.trials 
            if 'full_result' in trial.user_attrs]

# Salvar resultados
df_results = pd.DataFrame(results)
df_results.to_csv('optuna_results_v3.csv', index=False)

# Mostrar melhores parâmetros
print("🏆 MELHORES HIPERPARÂMETROS (Optuna):")
print("="*80)
for key, value in study.best_params.items():
    print(f"{key:25s}: {value}")
print("="*80)

# Visualização Optuna
try:
    from optuna.visualization import plot_optimization_history, plot_param_importances
    
    # Histórico de otimização
    fig1 = plot_optimization_history(study)
    fig1.write_image('optuna_history.png')
    fig1.show()
    
    # Importância dos parâmetros
    fig2 = plot_param_importances(study)
    fig2.write_image('optuna_importance.png')
    fig2.show()
    
    print("📊 Gráficos salvos: optuna_history.png, optuna_importance.png")
except Exception as e:
    print(f"⚠️ Não foi possível gerar visualizações Optuna: {e}")
    print("   Instale: pip install plotly kaleido")

  0%|          | 0/100 [00:00<?, ?it/s]

================================================================================
🧪 EXPERIMENTO 0
================================================================================
Context Length: 275 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  0%|          | 0/100 [01:05<?, ?it/s]

✅ Experimento 0 concluído!
   Val Loss: 0.026189 | RMSE: 0.161829
[I 2026-02-17 11:30:01,927] Trial 0 finished with value: 0.16182914320015943 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 0 with value: 0.16182914320015943.

Best trial: 0. Best value: 0.161829:   1%|          | 1/100 [01:05<1:48:47, 65.94s/it]

================================================================================
🧪 EXPERIMENTO 1
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 0. Best value: 0.161829:   1%|          | 1/100 [02:42<1:48:47, 65.94s/it]

✅ Experimento 1 concluído!
   Val Loss: 0.026029 | RMSE: 0.161334
[I 2026-02-17 11:31:39,839] Trial 1 finished with value: 0.16133420669508758 and parameters: {'lags': 9, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 1 with value: 0.16133420669508758.

Best trial: 1. Best value: 0.161334:   2%|▏         | 2/100 [02:43<2:18:09, 84.58s/it]

================================================================================
🧪 EXPERIMENTO 2
================================================================================
Context Length: 300 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 1. Best value: 0.161334:   2%|▏         | 2/100 [04:02<2:18:09, 84.58s/it]

✅ Experimento 2 concluído!
   Val Loss: 0.027637 | RMSE: 0.166244
[I 2026-02-17 11:32:59,062] Trial 2 finished with value: 0.16624405796503372 and parameters: {'lags': 5, 'use_mean_features': False, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 1 with value: 0.16133420669508758.

Best trial: 1. Best value: 0.161334:   3%|▎         | 3/100 [04:02<2:12:49, 82.16s/it]

================================================================================
🧪 EXPERIMENTO 3
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 1. Best value: 0.161334:   3%|▎         | 3/100 [05:46<2:12:49, 82.16s/it]

✅ Experimento 3 concluído!
   Val Loss: 0.022915 | RMSE: 0.151377
[I 2026-02-17 11:34:43,118] Trial 3 finished with value: 0.15137689620845593 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:   4%|▍         | 4/100 [05:46<2:25:17, 90.81s/it]

================================================================================
🧪 EXPERIMENTO 4
================================================================================
Context Length: 350 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:   4%|▍         | 4/100 [07:42<2:25:17, 90.81s/it]

✅ Experimento 4 concluído!
   Val Loss: 0.027244 | RMSE: 0.165057
[I 2026-02-17 11:36:38,985] Trial 4 finished with value: 0.16505739572939093 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 350, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:   5%|▌         | 5/100 [07:42<2:38:07, 99.87s/it]

================================================================================
🧪 EXPERIMENTO 5
================================================================================
Context Length: 275 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:   5%|▌         | 5/100 [08:56<2:38:07, 99.87s/it]

✅ Experimento 5 concluído!
   Val Loss: 0.026908 | RMSE: 0.164035
[I 2026-02-17 11:37:53,645] Trial 5 finished with value: 0.1640351533805061 and parameters: {'lags': 7, 'use_mean_features': False, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:   6%|▌         | 6/100 [08:57<2:22:54, 91.21s/it]

================================================================================
🧪 EXPERIMENTO 6
================================================================================
Context Length: 300 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:   6%|▌         | 6/100 [10:14<2:22:54, 91.21s/it]

✅ Experimento 6 concluído!
   Val Loss: 0.026625 | RMSE: 0.163171
[I 2026-02-17 11:39:11,195] Trial 6 finished with value: 0.16317122051235972 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:   7%|▋         | 7/100 [10:14<2:14:30, 86.78s/it]

================================================================================
🧪 EXPERIMENTO 7
================================================================================
Context Length: 275 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:   7%|▋         | 7/100 [13:57<2:14:30, 86.78s/it]

✅ Experimento 7 concluído!
   Val Loss: 0.026515 | RMSE: 0.162835
[I 2026-02-17 11:42:53,923] Trial 7 finished with value: 0.16283523683617313 and parameters: {'lags': 9, 'use_mean_features': True, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:   8%|▊         | 8/100 [13:57<3:19:31, 130.13s/it]

================================================================================
🧪 EXPERIMENTO 8
================================================================================
Context Length: 350 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:   8%|▊         | 8/100 [18:20<3:19:31, 130.13s/it]

✅ Experimento 8 concluído!
   Val Loss: 0.029194 | RMSE: 0.170864
[I 2026-02-17 11:47:16,938] Trial 8 finished with value: 0.17086391100206336 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 350, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:   9%|▉         | 9/100 [18:20<4:20:22, 171.67s/it]

================================================================================
🧪 EXPERIMENTO 9
================================================================================
Context Length: 300 | Horizon: 1
d_model: 64, heads: 16, layers: 5
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:   9%|▉         | 9/100 [20:40<4:20:22, 171.67s/it]

✅ Experimento 9 concluído!
   Val Loss: 0.028672 | RMSE: 0.169328
[I 2026-02-17 11:49:36,878] Trial 9 finished with value: 0.16932826107273477 and parameters: {'lags': 9, 'use_mean_features': True, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  10%|█         | 10/100 [20:40<4:02:38, 161.77s/it]

================================================================================
🧪 EXPERIMENTO 10
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  10%|█         | 10/100 [24:30<4:02:38, 161.77s/it]

✅ Experimento 10 concluído!
   Val Loss: 0.026268 | RMSE: 0.162074
[I 2026-02-17 11:53:27,695] Trial 10 finished with value: 0.16207431506006748 and parameters: {'lags': 3, 'use_mean_features': False, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  11%|█         | 11/100 [24:31<4:31:18, 182.90s/it]

================================================================================
🧪 EXPERIMENTO 11
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  11%|█         | 11/100 [26:20<4:31:18, 182.90s/it]

✅ Experimento 11 concluído!
   Val Loss: 0.028599 | RMSE: 0.169113
[I 2026-02-17 11:55:17,659] Trial 11 finished with value: 0.16911333471831386 and parameters: {'lags': 9, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  12%|█▏        | 12/100 [26:21<3:55:44, 160.73s/it]

================================================================================
🧪 EXPERIMENTO 12
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  12%|█▏        | 12/100 [28:01<3:55:44, 160.73s/it]

✅ Experimento 12 concluído!
   Val Loss: 0.024482 | RMSE: 0.156467
[I 2026-02-17 11:56:58,325] Trial 12 finished with value: 0.15646735213500798 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  13%|█▎        | 13/100 [28:02<3:26:45, 142.60s/it]

================================================================================
🧪 EXPERIMENTO 13
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  13%|█▎        | 13/100 [29:27<3:26:45, 142.60s/it]

✅ Experimento 13 concluído!
   Val Loss: 0.026974 | RMSE: 0.164238
[I 2026-02-17 11:58:23,882] Trial 13 finished with value: 0.16423813183755345 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  14%|█▍        | 14/100 [29:27<2:59:35, 125.29s/it]

================================================================================
🧪 EXPERIMENTO 14
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  14%|█▍        | 14/100 [30:51<2:59:35, 125.29s/it]

✅ Experimento 14 concluído!
   Val Loss: 0.025922 | RMSE: 0.161003
[I 2026-02-17 11:59:48,291] Trial 14 finished with value: 0.16100321094868045 and parameters: {'lags': 3, 'use_mean_features': False, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  15%|█▌        | 15/100 [30:52<2:40:06, 113.02s/it]

================================================================================
🧪 EXPERIMENTO 15
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  15%|█▌        | 15/100 [32:36<2:40:06, 113.02s/it]

✅ Experimento 15 concluído!
   Val Loss: 0.025922 | RMSE: 0.161003
[I 2026-02-17 12:01:33,831] Trial 15 finished with value: 0.16100321094868045 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  16%|█▌        | 16/100 [32:37<2:35:02, 110.74s/it]

================================================================================
🧪 EXPERIMENTO 16
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  16%|█▌        | 16/100 [33:46<2:35:02, 110.74s/it]

✅ Experimento 16 concluído!
   Val Loss: 0.024449 | RMSE: 0.156363
[I 2026-02-17 12:02:43,244] Trial 16 finished with value: 0.15636276705819177 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  17%|█▋        | 17/100 [33:46<2:15:51, 98.21s/it]

================================================================================
🧪 EXPERIMENTO 17
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  17%|█▋        | 17/100 [34:20<2:15:51, 98.21s/it]

✅ Experimento 17 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:03:17,071] Trial 17 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  18%|█▊        | 18/100 [34:20<1:47:46, 78.86s/it]

================================================================================
🧪 EXPERIMENTO 18
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  18%|█▊        | 18/100 [35:41<1:47:46, 78.86s/it]

✅ Experimento 18 concluído!
   Val Loss: 0.027233 | RMSE: 0.165023
[I 2026-02-17 12:04:38,847] Trial 18 finished with value: 0.16502273636824163 and parameters: {'lags': 7, 'use_mean_features': False, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  19%|█▉        | 19/100 [35:42<1:47:39, 79.74s/it]

================================================================================
🧪 EXPERIMENTO 19
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  19%|█▉        | 19/100 [36:16<1:47:39, 79.74s/it]

✅ Experimento 19 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:05:13,527] Trial 19 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  20%|██        | 20/100 [36:16<1:28:16, 66.21s/it]

================================================================================
🧪 EXPERIMENTO 20
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  20%|██        | 20/100 [36:57<1:28:16, 66.21s/it]

✅ Experimento 20 concluído!
   Val Loss: 0.026063 | RMSE: 0.161440
[I 2026-02-17 12:05:54,774] Trial 20 finished with value: 0.16143957472600406 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  21%|██        | 21/100 [36:58<1:17:19, 58.73s/it]

================================================================================
🧪 EXPERIMENTO 21
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  21%|██        | 21/100 [37:32<1:17:19, 58.73s/it]

✅ Experimento 21 concluído!
   Val Loss: 0.024482 | RMSE: 0.156467
[I 2026-02-17 12:06:28,996] Trial 21 finished with value: 0.15646735213500798 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  22%|██▏       | 22/100 [37:32<1:06:46, 51.37s/it]

================================================================================
🧪 EXPERIMENTO 22
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  22%|██▏       | 22/100 [38:06<1:06:46, 51.37s/it]

✅ Experimento 22 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:07:02,921] Trial 22 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  23%|██▎       | 23/100 [38:06<59:11, 46.13s/it]

================================================================================
🧪 EXPERIMENTO 23
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  23%|██▎       | 23/100 [38:36<59:11, 46.13s/it]

✅ Experimento 23 concluído!
   Val Loss: 0.026974 | RMSE: 0.164238
[I 2026-02-17 12:07:33,776] Trial 23 finished with value: 0.16423813183755345 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  24%|██▍       | 24/100 [38:37<52:37, 41.55s/it]

================================================================================
🧪 EXPERIMENTO 24
================================================================================
Context Length: 350 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  24%|██▍       | 24/100 [39:11<52:37, 41.55s/it]

✅ Experimento 24 concluído!
   Val Loss: 0.028051 | RMSE: 0.167485
[I 2026-02-17 12:08:08,830] Trial 24 finished with value: 0.1674847004525437 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 350, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  25%|██▌       | 25/100 [39:12<49:29, 39.60s/it]

================================================================================
🧪 EXPERIMENTO 25
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  25%|██▌       | 25/100 [39:45<49:29, 39.60s/it]

✅ Experimento 25 concluído!
   Val Loss: 0.025000 | RMSE: 0.158113
[I 2026-02-17 12:08:42,588] Trial 25 finished with value: 0.15811329516525202 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  26%|██▌       | 26/100 [39:45<46:40, 37.85s/it]

================================================================================
🧪 EXPERIMENTO 26
================================================================================
Context Length: 256 | Horizon: 1
d_model: 64, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  26%|██▌       | 26/100 [40:51<46:40, 37.85s/it]

✅ Experimento 26 concluído!
   Val Loss: 0.026433 | RMSE: 0.162582
[I 2026-02-17 12:09:48,086] Trial 26 finished with value: 0.1625815890510041 and parameters: {'lags': 3, 'use_mean_features': False, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  27%|██▋       | 27/100 [40:51<56:08, 46.14s/it]

================================================================================
🧪 EXPERIMENTO 27
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  27%|██▋       | 27/100 [41:30<56:08, 46.14s/it]

✅ Experimento 27 concluído!
   Val Loss: 0.026364 | RMSE: 0.162370
[I 2026-02-17 12:10:27,690] Trial 27 finished with value: 0.16237047149915604 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  28%|██▊       | 28/100 [41:31<53:01, 44.19s/it]

================================================================================
🧪 EXPERIMENTO 28
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

✅ Experimento 28 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819

Best trial: 3. Best value: 0.151377:  28%|██▊       | 28/100 [42:32<53:01, 44.19s/it]

[I 2026-02-17 12:11:29,249] Trial 28 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  29%|██▉       | 29/100 [42:34<58:58, 49.84s/it]

================================================================================
🧪 EXPERIMENTO 29
================================================================================
Context Length: 275 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  29%|██▉       | 29/100 [43:18<58:58, 49.84s/it]

✅ Experimento 29 concluído!
   Val Loss: 0.025923 | RMSE: 0.161006
[I 2026-02-17 12:12:15,493] Trial 29 finished with value: 0.16100609738675972 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  30%|███       | 30/100 [43:19<56:27, 48.39s/it]

================================================================================
🧪 EXPERIMENTO 30
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  30%|███       | 30/100 [44:20<56:27, 48.39s/it]

✅ Experimento 30 concluído!
   Val Loss: 0.027348 | RMSE: 0.165373
[I 2026-02-17 12:13:17,400] Trial 30 finished with value: 0.16537326629750623 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  31%|███       | 31/100 [44:21<1:00:21, 52.48s/it]

================================================================================
🧪 EXPERIMENTO 31
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  31%|███       | 31/100 [45:15<1:00:21, 52.48s/it]

✅ Experimento 31 concluído!
   Val Loss: 0.024482 | RMSE: 0.156467
[I 2026-02-17 12:14:12,372] Trial 31 finished with value: 0.15646735213500798 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  32%|███▏      | 32/100 [45:16<1:00:18, 53.22s/it]

================================================================================
🧪 EXPERIMENTO 32
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  32%|███▏      | 32/100 [46:22<1:00:18, 53.22s/it]

✅ Experimento 32 concluído!
   Val Loss: 0.026974 | RMSE: 0.164238
[I 2026-02-17 12:15:19,286] Trial 32 finished with value: 0.16423813183755345 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  33%|███▎      | 33/100 [46:25<1:04:53, 58.11s/it]

================================================================================
🧪 EXPERIMENTO 33
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  33%|███▎      | 33/100 [47:30<1:04:53, 58.11s/it]

✅ Experimento 33 concluído!
   Val Loss: 0.025922 | RMSE: 0.161003
[I 2026-02-17 12:16:27,179] Trial 33 finished with value: 0.16100321094868045 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  34%|███▍      | 34/100 [47:31<1:06:33, 60.51s/it]

================================================================================
🧪 EXPERIMENTO 34
================================================================================
Context Length: 300 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  34%|███▍      | 34/100 [48:27<1:06:33, 60.51s/it]

✅ Experimento 34 concluído!
   Val Loss: 0.027039 | RMSE: 0.164434
[I 2026-02-17 12:17:24,611] Trial 34 finished with value: 0.16443396137240407 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  35%|███▌      | 35/100 [48:28<1:04:11, 59.26s/it]

================================================================================
🧪 EXPERIMENTO 35
================================================================================
Context Length: 350 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  35%|███▌      | 35/100 [49:34<1:04:11, 59.26s/it]

✅ Experimento 35 concluído!
   Val Loss: 0.027616 | RMSE: 0.166181
[I 2026-02-17 12:18:31,013] Trial 35 finished with value: 0.16618064084267606 and parameters: {'lags': 9, 'use_mean_features': True, 'context_length': 350, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  36%|███▌      | 36/100 [49:34<1:05:39, 61.56s/it]

================================================================================
🧪 EXPERIMENTO 36
================================================================================
Context Length: 256 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  36%|███▌      | 36/100 [50:03<1:05:39, 61.56s/it]

✅ Experimento 36 concluído!
   Val Loss: 0.026075 | RMSE: 0.161478
[I 2026-02-17 12:19:00,584] Trial 36 finished with value: 0.16147812919367907 and parameters: {'lags': 7, 'use_mean_features': False, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  37%|███▋      | 37/100 [50:03<54:22, 51.78s/it]

================================================================================
🧪 EXPERIMENTO 37
================================================================================
Context Length: 275 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  37%|███▋      | 37/100 [50:39<54:22, 51.78s/it]

✅ Experimento 37 concluído!
   Val Loss: 0.025493 | RMSE: 0.159666
[I 2026-02-17 12:19:36,543] Trial 37 finished with value: 0.15966587473578192 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  38%|███▊      | 38/100 [50:39<48:36, 47.04s/it]

================================================================================
🧪 EXPERIMENTO 38
================================================================================
Context Length: 300 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  38%|███▊      | 38/100 [51:12<48:36, 47.04s/it]

✅ Experimento 38 concluído!
   Val Loss: 0.026537 | RMSE: 0.162901
[I 2026-02-17 12:20:09,322] Trial 38 finished with value: 0.16290118551440524 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  39%|███▉      | 39/100 [51:12<43:28, 42.76s/it]

================================================================================
🧪 EXPERIMENTO 39
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  39%|███▉      | 39/100 [52:07<43:28, 42.76s/it]

✅ Experimento 39 concluído!
   Val Loss: 0.028322 | RMSE: 0.168291
[I 2026-02-17 12:21:04,129] Trial 39 finished with value: 0.16829136428438288 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  40%|████      | 40/100 [52:07<46:23, 46.39s/it]

================================================================================
🧪 EXPERIMENTO 40
================================================================================
Context Length: 350 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  40%|████      | 40/100 [52:49<46:23, 46.39s/it]

✅ Experimento 40 concluído!
   Val Loss: 0.028787 | RMSE: 0.169669
[I 2026-02-17 12:21:45,987] Trial 40 finished with value: 0.16966879841718133 and parameters: {'lags': 9, 'use_mean_features': False, 'context_length': 350, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  41%|████      | 41/100 [52:49<44:15, 45.01s/it]

================================================================================
🧪 EXPERIMENTO 41
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  41%|████      | 41/100 [53:23<44:15, 45.01s/it]

✅ Experimento 41 concluído!
   Val Loss: 0.025319 | RMSE: 0.159119
[I 2026-02-17 12:22:20,410] Trial 41 finished with value: 0.1591191088776355 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  42%|████▏     | 42/100 [53:23<40:28, 41.86s/it]

================================================================================
🧪 EXPERIMENTO 42
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  42%|████▏     | 42/100 [53:55<40:28, 41.86s/it]

✅ Experimento 42 concluído!
   Val Loss: 0.026974 | RMSE: 0.164238
[I 2026-02-17 12:22:51,965] Trial 42 finished with value: 0.16423813183755345 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  43%|████▎     | 43/100 [53:55<36:48, 38.74s/it]

================================================================================
🧪 EXPERIMENTO 43
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  43%|████▎     | 43/100 [54:26<36:48, 38.74s/it]

✅ Experimento 43 concluído!
   Val Loss: 0.025922 | RMSE: 0.161003
[I 2026-02-17 12:23:22,890] Trial 43 finished with value: 0.16100321094868045 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  44%|████▍     | 44/100 [54:26<33:57, 36.39s/it]

================================================================================
🧪 EXPERIMENTO 44
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  44%|████▍     | 44/100 [55:07<33:57, 36.39s/it]

✅ Experimento 44 concluído!
   Val Loss: 0.026463 | RMSE: 0.162675
[I 2026-02-17 12:24:04,620] Trial 44 finished with value: 0.16267453343754082 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  45%|████▌     | 45/100 [55:07<34:49, 38.00s/it]

================================================================================
🧪 EXPERIMENTO 45
================================================================================
Context Length: 275 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  45%|████▌     | 45/100 [56:23<34:49, 38.00s/it]

✅ Experimento 45 concluído!
   Val Loss: 0.029910 | RMSE: 0.172946
[I 2026-02-17 12:25:19,957] Trial 45 finished with value: 0.17294638128984752 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  46%|████▌     | 46/100 [56:23<44:16, 49.20s/it]

================================================================================
🧪 EXPERIMENTO 46
================================================================================
Context Length: 256 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  46%|████▌     | 46/100 [56:52<44:16, 49.20s/it]

✅ Experimento 46 concluído!
   Val Loss: 0.026246 | RMSE: 0.162007
[I 2026-02-17 12:25:49,835] Trial 46 finished with value: 0.16200700078145458 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  47%|████▋     | 47/100 [56:53<38:20, 43.40s/it]

================================================================================
🧪 EXPERIMENTO 47
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  47%|████▋     | 47/100 [57:24<38:20, 43.40s/it]

✅ Experimento 47 concluído!
   Val Loss: 0.027757 | RMSE: 0.166604
[I 2026-02-17 12:26:21,150] Trial 47 finished with value: 0.16660353960158766 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  48%|████▊     | 48/100 [57:24<34:28, 39.78s/it]

================================================================================
🧪 EXPERIMENTO 48
================================================================================
Context Length: 300 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  48%|████▊     | 48/100 [58:02<34:28, 39.78s/it]

✅ Experimento 48 concluído!
   Val Loss: 0.027643 | RMSE: 0.166262
[I 2026-02-17 12:26:59,244] Trial 48 finished with value: 0.16626242076753445 and parameters: {'lags': 9, 'use_mean_features': False, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  49%|████▉     | 49/100 [58:02<33:23, 39.28s/it]

================================================================================
🧪 EXPERIMENTO 49
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  49%|████▉     | 49/100 [59:18<33:23, 39.28s/it]

✅ Experimento 49 concluído!
   Val Loss: 0.025773 | RMSE: 0.160541
[I 2026-02-17 12:28:15,368] Trial 49 finished with value: 0.16054090966792783 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  50%|█████     | 50/100 [59:18<41:56, 50.32s/it]

================================================================================
🧪 EXPERIMENTO 50
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  50%|█████     | 50/100 [59:52<41:56, 50.32s/it]

✅ Experimento 50 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:28:49,723] Trial 50 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  51%|█████     | 51/100 [59:53<37:11, 45.54s/it]

================================================================================
🧪 EXPERIMENTO 51
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  51%|█████     | 51/100 [1:00:26<37:11, 45.54s/it]

✅ Experimento 51 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:29:23,829] Trial 51 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  52%|█████▏    | 52/100 [1:00:27<33:40, 42.10s/it]

================================================================================
🧪 EXPERIMENTO 52
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  52%|█████▏    | 52/100 [1:01:00<33:40, 42.10s/it]

✅ Experimento 52 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:29:57,597] Trial 52 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  53%|█████▎    | 53/100 [1:01:00<31:01, 39.61s/it]

================================================================================
🧪 EXPERIMENTO 53
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  53%|█████▎    | 53/100 [1:01:35<31:01, 39.61s/it]

✅ Experimento 53 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:30:31,985] Trial 53 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  54%|█████▍    | 54/100 [1:01:35<29:09, 38.04s/it]

================================================================================
🧪 EXPERIMENTO 54
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  54%|█████▍    | 54/100 [1:02:09<29:09, 38.04s/it]

✅ Experimento 54 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:31:06,411] Trial 54 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  55%|█████▌    | 55/100 [1:02:09<27:42, 36.95s/it]

================================================================================
🧪 EXPERIMENTO 55
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  55%|█████▌    | 55/100 [1:02:43<27:42, 36.95s/it]

✅ Experimento 55 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 12:31:40,231] Trial 55 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  56%|█████▌    | 56/100 [1:02:43<26:24, 36.02s/it]

================================================================================
🧪 EXPERIMENTO 56
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  56%|█████▌    | 56/100 [1:03:44<26:24, 36.02s/it]

✅ Experimento 56 concluído!
   Val Loss: 0.026726 | RMSE: 0.163480
[I 2026-02-17 12:32:41,173] Trial 56 finished with value: 0.16347980906226325 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  57%|█████▋    | 57/100 [1:03:45<31:17, 43.66s/it]

================================================================================
🧪 EXPERIMENTO 57
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  57%|█████▋    | 57/100 [1:04:23<31:17, 43.66s/it]

✅ Experimento 57 concluído!
   Val Loss: 0.024250 | RMSE: 0.155724
[I 2026-02-17 12:33:20,622] Trial 57 finished with value: 0.15572447615569202 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  58%|█████▊    | 58/100 [1:04:24<29:34, 42.24s/it]

================================================================================
🧪 EXPERIMENTO 58
================================================================================
Context Length: 350 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  58%|█████▊    | 58/100 [1:05:23<29:34, 42.24s/it]

✅ Experimento 58 concluído!
   Val Loss: 0.027411 | RMSE: 0.165561
[I 2026-02-17 12:34:20,254] Trial 58 finished with value: 0.16556132370101423 and parameters: {'lags': 7, 'use_mean_features': False, 'context_length': 350, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  59%|█████▉    | 59/100 [1:05:24<32:39, 47.78s/it]

================================================================================
🧪 EXPERIMENTO 59
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  59%|█████▉    | 59/100 [1:07:27<32:39, 47.78s/it]

✅ Experimento 59 concluído!
   Val Loss: 0.025005 | RMSE: 0.158129
[I 2026-02-17 12:36:24,628] Trial 59 finished with value: 0.15812898005124332 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  60%|██████    | 60/100 [1:07:29<47:16, 70.91s/it]

================================================================================
🧪 EXPERIMENTO 60
================================================================================
Context Length: 275 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  60%|██████    | 60/100 [1:08:10<47:16, 70.91s/it]

✅ Experimento 60 concluído!
   Val Loss: 0.025932 | RMSE: 0.161034
[I 2026-02-17 12:37:06,887] Trial 60 finished with value: 0.16103382538013614 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  61%|██████    | 61/100 [1:08:10<40:11, 61.84s/it]

================================================================================
🧪 EXPERIMENTO 61
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  61%|██████    | 61/100 [1:08:48<40:11, 61.84s/it]

✅ Experimento 61 concluído!
   Val Loss: 0.024585 | RMSE: 0.156797
[I 2026-02-17 12:37:44,927] Trial 61 finished with value: 0.15679664357106038 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  62%|██████▏   | 62/100 [1:08:48<34:38, 54.70s/it]

================================================================================
🧪 EXPERIMENTO 62
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  62%|██████▏   | 62/100 [1:09:42<34:38, 54.70s/it]

✅ Experimento 62 concluído!
   Val Loss: 0.027757 | RMSE: 0.166604
[I 2026-02-17 12:38:39,253] Trial 62 finished with value: 0.16660353960158766 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  63%|██████▎   | 63/100 [1:09:43<33:45, 54.74s/it]

================================================================================
🧪 EXPERIMENTO 63
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  63%|██████▎   | 63/100 [1:10:24<33:45, 54.74s/it]

✅ Experimento 63 concluído!
   Val Loss: 0.024585 | RMSE: 0.156797
[I 2026-02-17 12:39:21,254] Trial 63 finished with value: 0.15679664357106038 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  64%|██████▍   | 64/100 [1:10:24<30:27, 50.77s/it]

================================================================================
🧪 EXPERIMENTO 64
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  64%|██████▍   | 64/100 [1:11:08<30:27, 50.77s/it]

✅ Experimento 64 concluído!
   Val Loss: 0.027757 | RMSE: 0.166604
[I 2026-02-17 12:40:05,508] Trial 64 finished with value: 0.16660353960158766 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  65%|██████▌   | 65/100 [1:11:09<28:30, 48.88s/it]

================================================================================
🧪 EXPERIMENTO 65
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  65%|██████▌   | 65/100 [1:12:34<28:30, 48.88s/it]

✅ Experimento 65 concluído!
   Val Loss: 0.026095 | RMSE: 0.161540
[I 2026-02-17 12:41:31,525] Trial 65 finished with value: 0.1615402561181835 and parameters: {'lags': 9, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  66%|██████▌   | 66/100 [1:12:35<34:00, 60.03s/it]

================================================================================
🧪 EXPERIMENTO 66
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  66%|██████▌   | 66/100 [1:13:34<34:00, 60.03s/it]

✅ Experimento 66 concluído!
   Val Loss: 0.026011 | RMSE: 0.161281
[I 2026-02-17 12:42:31,293] Trial 66 finished with value: 0.16128074328899705 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  67%|██████▋   | 67/100 [1:13:34<32:56, 59.88s/it]

================================================================================
🧪 EXPERIMENTO 67
================================================================================
Context Length: 300 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  67%|██████▋   | 67/100 [1:14:16<32:56, 59.88s/it]

✅ Experimento 67 concluído!
   Val Loss: 0.024901 | RMSE: 0.157802
[I 2026-02-17 12:43:13,042] Trial 67 finished with value: 0.1578015422793723 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.15137689620845593.

Best trial: 3. Best value: 0.151377:  68%|██████▊   | 68/100 [1:14:16<29:02, 54.44s/it]

================================================================================
🧪 EXPERIMENTO 68
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.151377:  68%|██████▊   | 68/100 [1:14:54<29:02, 54.44s/it]

✅ Experimento 68 concluído!
   Val Loss: 0.021630 | RMSE: 0.147071
[I 2026-02-17 12:43:51,583] Trial 68 finished with value: 0.1470714946461214 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  69%|██████▉   | 69/100 [1:14:54<25:39, 49.66s/it]

================================================================================
🧪 EXPERIMENTO 69
================================================================================
Context Length: 256 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  69%|██████▉   | 69/100 [1:15:25<25:39, 49.66s/it]

✅ Experimento 69 concluído!
   Val Loss: 0.026480 | RMSE: 0.162726
[I 2026-02-17 12:44:22,286] Trial 69 finished with value: 0.16272618251622295 and parameters: {'lags': 7, 'use_mean_features': False, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  70%|███████   | 70/100 [1:15:25<21:59, 43.98s/it]

================================================================================
🧪 EXPERIMENTO 70
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  70%|███████   | 70/100 [1:17:06<21:59, 43.98s/it]

✅ Experimento 70 concluído!
   Val Loss: 0.024595 | RMSE: 0.156829
[I 2026-02-17 12:46:03,506] Trial 70 finished with value: 0.156829159971423 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  71%|███████   | 71/100 [1:17:06<29:33, 61.16s/it]

================================================================================
🧪 EXPERIMENTO 71
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  71%|███████   | 71/100 [1:17:41<29:33, 61.16s/it]

✅ Experimento 71 concluído!
   Val Loss: 0.027757 | RMSE: 0.166604
[I 2026-02-17 12:46:38,073] Trial 71 finished with value: 0.16660353960158766 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  72%|███████▏  | 72/100 [1:17:41<24:48, 53.17s/it]

================================================================================
🧪 EXPERIMENTO 72
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  72%|███████▏  | 72/100 [1:18:17<24:48, 53.17s/it]

✅ Experimento 72 concluído!
   Val Loss: 0.024585 | RMSE: 0.156797
[I 2026-02-17 12:47:13,972] Trial 72 finished with value: 0.15679664357106038 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  73%|███████▎  | 73/100 [1:18:17<21:35, 47.98s/it]

================================================================================
🧪 EXPERIMENTO 73
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  73%|███████▎  | 73/100 [1:18:52<21:35, 47.98s/it]

✅ Experimento 73 concluído!
   Val Loss: 0.027757 | RMSE: 0.166604
[I 2026-02-17 12:47:48,977] Trial 73 finished with value: 0.16660353960158766 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  74%|███████▍  | 74/100 [1:18:52<19:07, 44.15s/it]

================================================================================
🧪 EXPERIMENTO 74
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  74%|███████▍  | 74/100 [1:19:39<19:07, 44.15s/it]

✅ Experimento 74 concluído!
   Val Loss: 0.024585 | RMSE: 0.156797
[I 2026-02-17 12:48:36,501] Trial 74 finished with value: 0.15679664357106038 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  75%|███████▌  | 75/100 [1:19:39<18:48, 45.13s/it]

================================================================================
🧪 EXPERIMENTO 75
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  75%|███████▌  | 75/100 [1:20:27<18:48, 45.13s/it]

✅ Experimento 75 concluído!
   Val Loss: 0.025298 | RMSE: 0.159054
[I 2026-02-17 12:49:24,635] Trial 75 finished with value: 0.15905386392610724 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  76%|███████▌  | 76/100 [1:20:28<18:24, 46.01s/it]

================================================================================
🧪 EXPERIMENTO 76
================================================================================
Context Length: 350 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  76%|███████▌  | 76/100 [1:21:18<18:24, 46.01s/it]

✅ Experimento 76 concluído!
   Val Loss: 0.026835 | RMSE: 0.163815
[I 2026-02-17 12:50:15,852] Trial 76 finished with value: 0.16381486300561945 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 350, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  77%|███████▋  | 77/100 [1:21:19<18:14, 47.59s/it]

================================================================================
🧪 EXPERIMENTO 77
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  77%|███████▋  | 77/100 [1:21:59<18:14, 47.59s/it]

✅ Experimento 77 concluído!
   Val Loss: 0.027671 | RMSE: 0.166347
[I 2026-02-17 12:50:56,001] Trial 77 finished with value: 0.16634686467044071 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  78%|███████▊  | 78/100 [1:21:59<16:37, 45.35s/it]

================================================================================
🧪 EXPERIMENTO 78
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  78%|███████▊  | 78/100 [1:23:26<16:37, 45.35s/it]

✅ Experimento 78 concluído!
   Val Loss: 0.025277 | RMSE: 0.158986
[I 2026-02-17 12:52:23,214] Trial 78 finished with value: 0.15898640722714566 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  79%|███████▉  | 79/100 [1:23:31<20:45, 59.29s/it]

================================================================================
🧪 EXPERIMENTO 79
================================================================================
Context Length: 275 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  79%|███████▉  | 79/100 [1:24:42<20:45, 59.29s/it]

✅ Experimento 79 concluído!
   Val Loss: 0.025162 | RMSE: 0.158626
[I 2026-02-17 12:53:39,005] Trial 79 finished with value: 0.15862598537886016 and parameters: {'lags': 5, 'use_mean_features': True, 'context_length': 275, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  80%|████████  | 80/100 [1:24:43<21:04, 63.24s/it]

================================================================================
🧪 EXPERIMENTO 80
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  80%|████████  | 80/100 [1:25:34<21:04, 63.24s/it]

✅ Experimento 80 concluído!
   Val Loss: 0.028704 | RMSE: 0.169422
[I 2026-02-17 12:54:31,752] Trial 80 finished with value: 0.16942212178642313 and parameters: {'lags': 9, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  81%|████████  | 81/100 [1:25:35<18:55, 59.75s/it]

================================================================================
🧪 EXPERIMENTO 81
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  81%|████████  | 81/100 [1:26:33<18:55, 59.75s/it]

✅ Experimento 81 concluído!
   Val Loss: 0.027757 | RMSE: 0.166604
[I 2026-02-17 12:55:30,375] Trial 81 finished with value: 0.16660353960158766 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  82%|████████▏ | 82/100 [1:26:34<17:51, 59.51s/it]

================================================================================
🧪 EXPERIMENTO 82
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  82%|████████▏ | 82/100 [1:27:24<17:51, 59.51s/it]

✅ Experimento 82 concluído!
   Val Loss: 0.024585 | RMSE: 0.156797
[I 2026-02-17 12:56:20,873] Trial 82 finished with value: 0.15679664357106038 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  83%|████████▎ | 83/100 [1:27:24<16:03, 56.69s/it]

================================================================================
🧪 EXPERIMENTO 83
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  83%|████████▎ | 83/100 [1:28:07<16:03, 56.69s/it]

✅ Experimento 83 concluído!
   Val Loss: 0.027757 | RMSE: 0.166604
[I 2026-02-17 12:57:04,345] Trial 83 finished with value: 0.16660353960158766 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  84%|████████▍ | 84/100 [1:28:07<14:03, 52.70s/it]

================================================================================
🧪 EXPERIMENTO 84
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  84%|████████▍ | 84/100 [1:30:13<14:03, 52.70s/it]

✅ Experimento 84 concluído!
   Val Loss: 0.024585 | RMSE: 0.156797
[I 2026-02-17 12:59:09,947] Trial 84 finished with value: 0.15679664357106038 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  85%|████████▌ | 85/100 [1:30:14<18:44, 74.95s/it]

================================================================================
🧪 EXPERIMENTO 85
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  85%|████████▌ | 85/100 [1:31:54<18:44, 74.95s/it]

✅ Experimento 85 concluído!
   Val Loss: 0.026837 | RMSE: 0.163819
[I 2026-02-17 13:00:51,830] Trial 85 finished with value: 0.1638187345906948 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  86%|████████▌ | 86/100 [1:31:55<19:18, 82.74s/it]

================================================================================
🧪 EXPERIMENTO 86
================================================================================
Context Length: 300 | Horizon: 1
d_model: 64, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  86%|████████▌ | 86/100 [1:33:17<19:18, 82.74s/it]

✅ Experimento 86 concluído!
   Val Loss: 0.026233 | RMSE: 0.161966
[I 2026-02-17 13:02:14,635] Trial 86 finished with value: 0.1619658236716729 and parameters: {'lags': 3, 'use_mean_features': False, 'context_length': 300, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  87%|████████▋ | 87/100 [1:33:18<17:55, 82.75s/it]

================================================================================
🧪 EXPERIMENTO 87
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  87%|████████▋ | 87/100 [1:34:55<17:55, 82.75s/it]

✅ Experimento 87 concluído!
   Val Loss: 0.027245 | RMSE: 0.165059
[I 2026-02-17 13:03:52,248] Trial 87 finished with value: 0.16505924078927708 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  88%|████████▊ | 88/100 [1:34:56<17:26, 87.23s/it]

================================================================================
🧪 EXPERIMENTO 88
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 5
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  88%|████████▊ | 88/100 [1:38:58<17:26, 87.23s/it]

✅ Experimento 88 concluído!
   Val Loss: 0.027459 | RMSE: 0.165707
[I 2026-02-17 13:07:55,147] Trial 88 finished with value: 0.16570728502712517 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 5, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  89%|████████▉ | 89/100 [1:38:58<24:33, 133.93s/it]

================================================================================
🧪 EXPERIMENTO 89
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  89%|████████▉ | 89/100 [1:40:14<24:33, 133.93s/it]

✅ Experimento 89 concluído!
   Val Loss: 0.029167 | RMSE: 0.170783
[I 2026-02-17 13:09:10,647] Trial 89 finished with value: 0.17078288940452527 and parameters: {'lags': 3, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.05, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  90%|█████████ | 90/100 [1:40:14<19:23, 116.35s/it]

================================================================================
🧪 EXPERIMENTO 90
================================================================================
Context Length: 325 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  90%|█████████ | 90/100 [1:42:29<19:23, 116.35s/it]

✅ Experimento 90 concluído!
   Val Loss: 0.026407 | RMSE: 0.162503
[I 2026-02-17 13:11:26,599] Trial 90 finished with value: 0.16250293710695224 and parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 325, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 68 with value: 0.1470714946461214.

Best trial: 68. Best value: 0.147071:  91%|█████████ | 91/100 [1:42:31<18:22, 122.48s/it]

================================================================================
🧪 EXPERIMENTO 91
================================================================================
Context Length: 256 | Horizon: 1
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 8
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 68. Best value: 0.147071:  91%|█████████ | 91/100 [1:45:01<18:22, 122.48s/it]

[W 2026-02-17 13:13:57,840] Trial 91 failed with parameters: {'lags': 7, 'use_mean_features': True, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 128, 'dropout': 0.1, 'patch_length': 8, 'learning_rate': 0.0005, 'batch_size': 32} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18780\822466487.py", line 26, in optuna_objective
    result = run_experiment(
             ^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18780\1616315580.py", line 105, in run_experiment
    train_result = trainer.train()
                   ^^^^^^^^^^^^^^^
  File "c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\transformers\trainer.py", line 2328, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\transformers\trainer.py", line 2672, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\transformers\trainer.py", line 4060, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\accelerate\accelerator.py", line 2852, in backward
    loss.backward(**kwargs)
  File "c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\torch\_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\torch\autograd\__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
[W 2026-02-17 13:13:58,608] Trial 91 failed with value None.

Best trial: 68. Best value: 0.147071:  91%|█████████ | 91/100 [1:45:05<10:23, 69.29s/it]

KeyboardInterrupt: