In [1]:
import sys
import pandas as pd
import numpy as np
import torch
import optuna
from datetime import datetime

from transformers import (
    EarlyStoppingCallback,
    PatchTSTConfig,
    PatchTSTForPrediction,
    Trainer,
    TrainingArguments    
)

import optuna
from optuna.samplers import TPESampler

import matplotlib.pyplot as plt

sys.path.append('../src')

from dataset import RepositorioDados
from models.har import HarModel
from models.transformer import compute_metrics, evaluate_and_visualize

# Detecta o dispositivo e a precisão usada nas operações
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.bfloat16 if (device.type == "cuda" and torch.cuda.is_bf16_supported()) else torch.float32
print(f"Device: {device} | Precision: {dtype}")

# Seed para resultados reproduzíveis
RANDOM_STATE = 42
torch.manual_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

c:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Device: cpu | Precision: torch.float32

In [25]:
# ==================== CONFIGURAÇÕES PRÉ-TREINAMENTO ====================
TIMESTAMP_COLUMN = 'timestamp'  # Coluna com timestamps em ms

# Tamanhos das janelas: histórico 7 dias, previsão 1 dia (dados diários)
CONTEXT_LENGTH = 512         # Janela histórica: x dias passados
FORECAST_HORIZON = 1        # Prever: x dias à frente

TRAIN_FRAC, VALID_FRAC = 0.7, 0.1  # Frações treino/validação/teste

# Hyperparâmetros do modelo
PATCH_LENGTH = 1            # Tamanho do patch (1=sem patchificação, mantém cada dia)
BATCH_SIZE = 32             # Samples por batch (reduzir se GPU memory limitada)
NUM_WORKERS = 0             # Workers para data loading (0 em Windows)
EPOCHS = 50                 # Reduzido: 50→30 (volatilidade tem ciclos curtos)
LEARNING_RATE = 1e-4        # Taxa de aprendizado

In [26]:
repo = RepositorioDados()

In [27]:
FEATURES = ["Vol_lag_1", "Vol_lag_2", "Vol_lag_3"]
TARGET_COLUMN = ['Vol']
ID_COLUMNS = []

In [28]:
tsp, train_ds, valid_ds, test_ds = repo.executar(
    timestamp_col=TIMESTAMP_COLUMN,
    train_frac=TRAIN_FRAC,
    valid_frac=VALID_FRAC,
    context_length=CONTEXT_LENGTH,
    features=FEATURES,
    target=TARGET_COLUMN,
    id_cols=ID_COLUMNS,
    forecast_horizon=FORECAST_HORIZON,
    use_mean_features=False,
    lags=3
)

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1279 amostras | Val: 256 | Teste: 512

In [29]:
train_ds.datasets[0].data_df

      timestamp       Vol  group
0    2017-11-30  2.618216      0
1    2017-12-01  0.700721      0
2    2017-12-02  0.182059      0
3    2017-12-03  1.475025      0
4    2017-12-04  0.422412      0
...         ...       ...    ...
1786 2022-10-21 -0.345558      0
1787 2022-10-22 -0.414484      0
1788 2022-10-23 -0.384091      0
1789 2022-10-24 -0.372276      0
1790 2022-10-25 -0.262344      0

[1791 rows x 3 columns]

In [30]:
# 1. Features
FEATURE_COMBINATIONS = {
    1: ["Vol_lag_1", "Vol_week_mean", "Vol_month_mean"],
    3: ["Vol_lag_1", "Vol_lag_2", "Vol_lag_3"],
}

# 2. Janelas temporais
CONTEXT_LENGTHS = [256, 512]
FORECAST_HORIZONS = [1]  # Manter fixo por enquanto

# 3. Hiperparâmetros do modelo
MODEL_PARAMS = {
    'd_model': [64, 128],
    'num_attention_heads': [8, 16],
    'num_hidden_layers': [2, 3],
    'ffn_dim': [256, 512],
    'dropout': [0.1, 0.2],
    'patch_length': [1, 16],
}

# 4. Hiperparâmetros de treinamento
TRAINING_PARAMS = {
    'learning_rate': [1e-4, 5e-4],
    'batch_size': [32, 64],
}

# Configurações fixas
FIXED_PARAMS = {
    'epochs': 10,  # Reduzido para grid search
    'early_stopping_patience': 3,
    'num_workers': 0,
    'train_frac': 0.7,
    'valid_frac': 0.1,
}

print("Espaços de busca definidos")
print(f"Total de combinações de features: {len(FEATURE_COMBINATIONS)}")
print(f"Total de combinações de context_length: {len(CONTEXT_LENGTHS)}")
print(f"Total de combinações de modelo: {np.prod([len(v) for v in MODEL_PARAMS.values()])}")
print(f"Total de combinações de treinamento: {np.prod([len(v) for v in TRAINING_PARAMS.values()])}")
total = len(FEATURE_COMBINATIONS) * len(CONTEXT_LENGTHS) * np.prod([len(v) for v in MODEL_PARAMS.values()]) * np.prod([len(v) for v in TRAINING_PARAMS.values()])
print(f"\n🔍 Total de experimentos: {int(total)}")

Espaços de busca definidos
Total de combinações de features: 2
Total de combinações de context_length: 2
Total de combinações de modelo: 64
Total de combinações de treinamento: 4

🔍 Total de experimentos: 1024

In [ ]:
def run_experiment(
    features,
    context_length,
    forecast_horizon,
    d_model,
    num_attention_heads,
    num_hidden_layers,
    ffn_dim,
    dropout,
    patch_length,
    learning_rate,
    batch_size,
    experiment_id,
    use_mean_features,
    lags
):
    """
    Executa um experimento completo com os parâmetros fornecidos.
    Retorna um dicionário com os resultados.
    
    trial: Optuna trial para pruning (opcional)
    """
    print(f"\n{'='*80}")
    print(f"🧪 EXPERIMENTO {experiment_id}")
    print(f"{'='*80}")
    print(f"Features: {features}")
    print(f"Context Length: {context_length}")
    print(f"d_model: {d_model}, heads: {num_attention_heads}, layers: {num_hidden_layers}")
    print(f"LR: {learning_rate}, Batch: {batch_size}, Patch: {patch_length}")
    print(f"{'='*80}\n")
    
    try:
        # Escolher configuração (rápida ou completa)
        config_params = FIXED_PARAMS
        
        # 1. Preparar dados
        tsp, train_ds, valid_ds, test_ds = repo.executar(
            timestamp_col=TIMESTAMP_COLUMN,
            train_frac=config_params['train_frac'],
            valid_frac=config_params['valid_frac'],
            context_length=context_length,
            features=features,
            target=TARGET_COLUMN,
            id_cols=ID_COLUMNS,
            forecast_horizon=forecast_horizon,
            use_mean_features=use_mean_features,
            lags=lags
        )
        
        # 2. Configurar modelo
        config = PatchTSTConfig(
            do_mask_input=False,
            context_length=context_length,
            patch_length=patch_length,
            num_input_channels=len(TARGET_COLUMN),
            patch_stride=patch_length,
            prediction_length=forecast_horizon,
            d_model=d_model,
            num_attention_heads=num_attention_heads,
            num_hidden_layers=num_hidden_layers,
            ffn_dim=ffn_dim,
            dropout=dropout,
            head_dropout=dropout,
            pooling_type=None,
            channel_attention=True,
            scaling='std',
            loss='mse',
            pre_norm=True,
            norm_type='batchnorm',
        )
        
        model = PatchTSTForPrediction(config=config).to(device).to(dtype)
        
        # 3. Configurar treinamento
        train_args = TrainingArguments(
            output_dir="./grid_search_temp",
            overwrite_output_dir=True,
            learning_rate=learning_rate,
            num_train_epochs=config_params['epochs'],
            do_eval=True,
            eval_strategy="epoch",
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            dataloader_num_workers=config_params['num_workers'],
            save_strategy="no",
            logging_strategy="epoch",
            logging_dir=None,
            load_best_model_at_end=False,
            metric_for_best_model="eval_loss",
            greater_is_better=False,
            label_names=["future_values"],
            report_to="none",
            fp16=(dtype == torch.float16),
            bf16=(dtype == torch.bfloat16),
        )
        
        early_stopping = EarlyStoppingCallback(
            early_stopping_patience=config_params['early_stopping_patience'],
            early_stopping_threshold=0.001
        )
        
        trainer = Trainer(
            model=model,
            args=train_args,
            train_dataset=train_ds,
            eval_dataset=valid_ds,
            compute_metrics=compute_metrics,
            callbacks=[early_stopping]
        )
        
        # 4. Treinar
        train_result = trainer.train()
        
        # 5. Avaliar no conjunto de validação
        eval_result = trainer.evaluate()
        
        # 6. Coletar métricas
        result = {
            'experiment_id': experiment_id,
            'features': str(features),
            'num_features': len(features),
            'context_length': context_length,
            'forecast_horizon': forecast_horizon,
            'd_model': d_model,
            'num_attention_heads': num_attention_heads,
            'num_hidden_layers': num_hidden_layers,
            'ffn_dim': ffn_dim,
            'dropout': dropout,
            'patch_length': patch_length,
            'learning_rate': learning_rate,
            'batch_size': batch_size,
            'train_loss': train_result.training_loss,
            'eval_loss': eval_result['eval_loss'],
            'eval_MSE': eval_result.get('eval_MSE', None),
            'eval_MAE': eval_result.get('eval_MAE', None),
            'eval_RMSE': eval_result.get('eval_RMSE', None),
            'eval_MAPE': eval_result.get('eval_MAPE', None),
            'epochs_trained': train_result.global_step // len(train_ds) * batch_size,
            'status': 'success'
        }
        
        print(f"✅ Experimento {experiment_id} concluído!")
        print(f"   Val Loss: {eval_result['eval_loss']:.6f} | RMSE: {result['eval_RMSE']:.6f}")
        
        # Limpar memória
        del model, trainer, train_ds, valid_ds, test_ds, tsp
        torch.cuda.empty_cache() if torch.cuda.is_available() else None
        
        return result
        
    except Exception as e:
        print(f"❌ Erro no experimento {experiment_id}: {str(e)}")
        return {
            'experiment_id': experiment_id,
            'features': str(features),
            'context_length': context_length,
            'd_model': d_model,
            'learning_rate': learning_rate,
            'batch_size': batch_size,
            'status': 'failed',
            'error': str(e)
        }

print("✓ Função run_experiment definida (com modo rápido)")

✓ Função run_experiment definida (com modo rápido)

In [32]:
def optuna_objective(trial):
    """
    Função objetivo para Optuna.
    Retorna a métrica a ser MINIMIZADA (eval_loss ou RMSE).
    """
    # Sugere hiperparâmetros a partir dos espaços definidos na célula 6
    features_idx = trial.suggest_categorical('features_idx', list(FEATURE_COMBINATIONS.keys()))
    features = FEATURE_COMBINATIONS[features_idx]

    context_length = trial.suggest_categorical('context_length', CONTEXT_LENGTHS)
    forecast_horizon = trial.suggest_categorical('forecast_horizon', FORECAST_HORIZONS)

    d_model = trial.suggest_categorical('d_model', MODEL_PARAMS['d_model'])
    num_attention_heads = trial.suggest_categorical('num_attention_heads', MODEL_PARAMS['num_attention_heads'])
    num_hidden_layers = trial.suggest_categorical('num_hidden_layers', MODEL_PARAMS['num_hidden_layers'])
    ffn_dim = trial.suggest_categorical('ffn_dim', MODEL_PARAMS['ffn_dim'])
    dropout = trial.suggest_categorical('dropout', MODEL_PARAMS['dropout'])
    patch_length = trial.suggest_categorical('patch_length', MODEL_PARAMS['patch_length'])

    learning_rate = trial.suggest_categorical('learning_rate', TRAINING_PARAMS['learning_rate'])
    batch_size = trial.suggest_categorical('batch_size', TRAINING_PARAMS['batch_size'])

    # Executar experimento
    result = run_experiment(
        features=features,
        context_length=context_length,
        forecast_horizon=forecast_horizon,
        d_model=d_model,
        num_attention_heads=num_attention_heads,
        num_hidden_layers=num_hidden_layers,
        ffn_dim=ffn_dim,
        dropout=dropout,
        patch_length=patch_length,
        learning_rate=learning_rate,
        batch_size=batch_size,
        experiment_id=trial.number,
        use_mean_features=True if features_idx == 1 else False,
        lags=features_idx
    )

    # Salvar resultado completo
    trial.set_user_attr('full_result', result)

    # Se falhou, retornar valor alto
    if result['status'] == 'failed':
        return float('inf')

    # Retornar métrica a minimizar
    return result['eval_RMSE']  # ou 'eval_loss'

In [33]:
study = optuna.create_study(
    direction='minimize',  # Minimizar RMSE
    sampler=TPESampler(seed=RANDOM_STATE),
    study_name='patchtst_optimization'
)

[I 2026-02-10 00:31:26,221] A new study created in memory with name: patchtst_optimization

In [34]:
start_time = datetime.now()

# Executar otimização
study.optimize(
    optuna_objective,
    n_trials=50,  # ⚡ REDUZIDO: 200 → 50
    show_progress_bar=True,
    callbacks=[
        lambda study, trial: study.trials_dataframe().to_csv(
            'optuna_results_partial.csv', index=False
        ) if trial.number % 5 == 0 else None
    ],
    gc_after_trial=True  # ⚡ NOVO: Libera memória após cada trial
)

end_time = datetime.now()
duration = end_time - start_time

print(f"\n{'='*80}")
print(f"✅ Busca Optuna concluída!")
print(f"⏱️ Tempo total: {duration}")
print(f"🏆 Melhor RMSE: {study.best_value:.6f}")
print(f"{'='*80}\n")

# Extrair resultados
results = [trial.user_attrs.get('full_result') for trial in study.trials 
            if 'full_result' in trial.user_attrs]

# Salvar resultados
df_results = pd.DataFrame(results)
df_results.to_csv('optuna_results.csv', index=False)

# Mostrar melhores parâmetros
print("🏆 MELHORES HIPERPARÂMETROS (Optuna):")
print("="*80)
for key, value in study.best_params.items():
    print(f"{key:25s}: {value}")
print("="*80)

# Visualização Optuna
try:
    from optuna.visualization import plot_optimization_history, plot_param_importances
    
    # Histórico de otimização
    fig1 = plot_optimization_history(study)
    fig1.write_image('optuna_history.png')
    fig1.show()
    
    # Importância dos parâmetros
    fig2 = plot_param_importances(study)
    fig2.write_image('optuna_importance.png')
    fig2.show()
    
    print("📊 Gráficos salvos: optuna_history.png, optuna_importance.png")
except Exception as e:
    print(f"⚠️ Não foi possível gerar visualizações Optuna: {e}")
    print("   Instale: pip install plotly kaleido")

  0%|          | 0/50 [00:00<?, ?it/s]

================================================================================
🧪 EXPERIMENTO 0
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 0. Best value: 0.164034:   2%|▏         | 1/50 [00:19<15:45, 19.29s/it]

✅ Experimento 0 concluído!
   Val Loss: 0.026907 | RMSE: 0.164034
[I 2026-02-10 00:31:45,391] Trial 0 finished with value: 0.16403414844590972 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 0 with value: 0.16403414844590972.

================================================================================
🧪 EXPERIMENTO 1
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 512
d_model: 128, heads: 16, layers: 2
LR: 0.0001, Batch: 32, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1278 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 0. Best value: 0.164034:   2%|▏         | 1/50 [12:53<15:45, 19.29s/it]

✅ Experimento 1 concluído!
   Val Loss: 0.042071 | RMSE: 0.205111
[I 2026-02-10 00:44:19,525] Trial 1 finished with value: 0.20511113763945277 and parameters: {'features_idx': 1, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 1, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 0 with value: 0.16403414844590972.

Best trial: 0. Best value: 0.164034:   4%|▍         | 2/50 [12:54<6:01:42, 452.13s/it]

================================================================================
🧪 EXPERIMENTO 2
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 512
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 64, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1279 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 0. Best value: 0.164034:   4%|▍         | 2/50 [13:16<6:01:42, 452.13s/it]

✅ Experimento 2 concluído!
   Val Loss: 0.032416 | RMSE: 0.180045
[I 2026-02-10 00:44:42,375] Trial 2 finished with value: 0.18004452439488342 and parameters: {'features_idx': 3, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 0 with value: 0.16403414844590972.

Best trial: 0. Best value: 0.164034:   6%|▌         | 3/50 [13:16<3:20:16, 255.67s/it]

================================================================================
🧪 EXPERIMENTO 3
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 0. Best value: 0.164034:   6%|▌         | 3/50 [13:44<3:20:16, 255.67s/it]

✅ Experimento 3 concluído!
   Val Loss: 0.026784 | RMSE: 0.163657
[I 2026-02-10 00:45:10,385] Trial 3 finished with value: 0.16365727266163665 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:   8%|▊         | 4/50 [13:44<2:07:06, 165.80s/it]

================================================================================
🧪 EXPERIMENTO 4
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 8, layers: 2
LR: 0.0001, Batch: 64, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:   8%|▊         | 4/50 [19:11<2:07:06, 165.80s/it]

✅ Experimento 4 concluído!
   Val Loss: 0.033393 | RMSE: 0.182737
[I 2026-02-10 00:50:37,665] Trial 4 finished with value: 0.18273719883270362 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 8, 'num_hidden_layers': 2, 'ffn_dim': 512, 'dropout': 0.1, 'patch_length': 1, 'learning_rate': 0.0001, 'batch_size': 64}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  10%|█         | 5/50 [19:12<2:48:10, 224.24s/it]

================================================================================
🧪 EXPERIMENTO 5
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 512
d_model: 64, heads: 16, layers: 2
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1279 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  10%|█         | 5/50 [19:35<2:48:10, 224.24s/it]

✅ Experimento 5 concluído!
   Val Loss: 0.034655 | RMSE: 0.186158
[I 2026-02-10 00:51:02,176] Trial 5 finished with value: 0.18615760678111787 and parameters: {'features_idx': 3, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  12%|█▏        | 6/50 [19:36<1:54:29, 156.14s/it]

================================================================================
🧪 EXPERIMENTO 6
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0005, Batch: 64, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  12%|█▏        | 6/50 [31:28<1:54:29, 156.14s/it]

✅ Experimento 6 concluído!
   Val Loss: 0.040753 | RMSE: 0.201874
[I 2026-02-10 01:02:54,712] Trial 6 finished with value: 0.20187350941335064 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 1, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  14%|█▍        | 7/50 [31:29<4:02:31, 338.40s/it]

================================================================================
🧪 EXPERIMENTO 7
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 64, heads: 8, layers: 3
LR: 0.0005, Batch: 64, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  14%|█▍        | 7/50 [37:23<4:02:31, 338.40s/it]

✅ Experimento 7 concluído!
   Val Loss: 0.031965 | RMSE: 0.178788
[I 2026-02-10 01:08:50,214] Trial 7 finished with value: 0.17878813196814802 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 8, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 1, 'learning_rate': 0.0005, 'batch_size': 64}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  16%|█▌        | 8/50 [37:26<4:00:52, 344.11s/it]

================================================================================
🧪 EXPERIMENTO 8
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 128, heads: 8, layers: 3
LR: 0.0001, Batch: 32, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  16%|█▌        | 8/50 [46:30<4:00:52, 344.11s/it]

✅ Experimento 8 concluído!
   Val Loss: 0.030733 | RMSE: 0.175307
[I 2026-02-10 01:17:57,114] Trial 8 finished with value: 0.17530697312372331 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 8, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 1, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  18%|█▊        | 9/50 [46:33<4:38:34, 407.67s/it]

================================================================================
🧪 EXPERIMENTO 9
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 8, layers: 2
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  18%|█▊        | 9/50 [46:54<4:38:34, 407.67s/it]

✅ Experimento 9 concluído!
   Val Loss: 0.026968 | RMSE: 0.164219
[I 2026-02-10 01:18:20,860] Trial 9 finished with value: 0.16421877139642144 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 8, 'num_hidden_layers': 2, 'ffn_dim': 512, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  20%|██        | 10/50 [46:54<3:12:14, 288.37s/it]

================================================================================
🧪 EXPERIMENTO 10
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 512
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1278 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  20%|██        | 10/50 [47:35<3:12:14, 288.37s/it]

✅ Experimento 10 concluído!
   Val Loss: 0.030639 | RMSE: 0.175041
[I 2026-02-10 01:19:01,435] Trial 10 finished with value: 0.1750412517700993 and parameters: {'features_idx': 1, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  22%|██▏       | 11/50 [47:35<2:18:09, 212.56s/it]

================================================================================
🧪 EXPERIMENTO 11
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  22%|██▏       | 11/50 [47:53<2:18:09, 212.56s/it]

✅ Experimento 11 concluído!
   Val Loss: 0.027043 | RMSE: 0.164448
[I 2026-02-10 01:19:20,055] Trial 11 finished with value: 0.16444779747604052 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  24%|██▍       | 12/50 [47:53<1:37:14, 153.54s/it]

================================================================================
🧪 EXPERIMENTO 12
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  24%|██▍       | 12/50 [48:18<1:37:14, 153.54s/it]

✅ Experimento 12 concluído!
   Val Loss: 0.026857 | RMSE: 0.163880
[I 2026-02-10 01:19:44,921] Trial 12 finished with value: 0.16388025834124065 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  26%|██▌       | 13/50 [48:18<1:10:38, 114.57s/it]

================================================================================
🧪 EXPERIMENTO 13
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Treino: 1534 amostras | Val: 256 | Teste: 512

Best trial: 3. Best value: 0.163657:  26%|██▌       | 13/50 [48:50<1:10:38, 114.57s/it]

✅ Experimento 13 concluído!
   Val Loss: 0.027054 | RMSE: 0.164482
[I 2026-02-10 01:20:16,411] Trial 13 finished with value: 0.16448184756988585 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  28%|██▊       | 14/50 [48:50<53:41, 89.47s/it]

================================================================================
🧪 EXPERIMENTO 14
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  28%|██▊       | 14/50 [49:14<53:41, 89.47s/it]

✅ Experimento 14 concluído!
   Val Loss: 0.027546 | RMSE: 0.165970
[I 2026-02-10 01:20:41,146] Trial 14 finished with value: 0.16597044273831973 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  30%|███       | 15/50 [49:15<40:48, 69.96s/it]

================================================================================
🧪 EXPERIMENTO 15
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  30%|███       | 15/50 [49:39<40:48, 69.96s/it]

✅ Experimento 15 concluído!
   Val Loss: 0.027362 | RMSE: 0.165416
[I 2026-02-10 01:21:06,049] Trial 15 finished with value: 0.16541595987518068 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  32%|███▏      | 16/50 [49:39<31:57, 56.40s/it]

================================================================================
🧪 EXPERIMENTO 16
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  32%|███▏      | 16/50 [50:00<31:57, 56.40s/it]

✅ Experimento 16 concluído!
   Val Loss: 0.028412 | RMSE: 0.168558
[I 2026-02-10 01:21:27,019] Trial 16 finished with value: 0.16855766497089555 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  34%|███▍      | 17/50 [50:00<25:09, 45.74s/it]

================================================================================
🧪 EXPERIMENTO 17
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  34%|███▍      | 17/50 [50:26<25:09, 45.74s/it]

✅ Experimento 17 concluído!
   Val Loss: 0.026857 | RMSE: 0.163880
[I 2026-02-10 01:21:52,695] Trial 17 finished with value: 0.16388025834124065 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  36%|███▌      | 18/50 [50:26<21:10, 39.71s/it]

================================================================================
🧪 EXPERIMENTO 18
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 512
d_model: 64, heads: 8, layers: 3
LR: 0.0001, Batch: 64, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1278 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  36%|███▌      | 18/50 [50:45<21:10, 39.71s/it]

✅ Experimento 18 concluído!
   Val Loss: 0.036587 | RMSE: 0.191278
[I 2026-02-10 01:22:11,899] Trial 18 finished with value: 0.19127841495281975 and parameters: {'features_idx': 1, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 8, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 64}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  38%|███▊      | 19/50 [50:45<17:20, 33.55s/it]

================================================================================
🧪 EXPERIMENTO 19
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  38%|███▊      | 19/50 [51:08<17:20, 33.55s/it]

✅ Experimento 19 concluído!
   Val Loss: 0.027868 | RMSE: 0.166937
[I 2026-02-10 01:22:34,470] Trial 19 finished with value: 0.1669367201746554 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  40%|████      | 20/50 [51:08<15:07, 30.26s/it]

================================================================================
🧪 EXPERIMENTO 20
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  40%|████      | 20/50 [51:47<15:07, 30.26s/it]

✅ Experimento 20 concluído!
   Val Loss: 0.027620 | RMSE: 0.166191
[I 2026-02-10 01:23:13,434] Trial 20 finished with value: 0.1661911877599211 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  42%|████▏     | 21/50 [51:47<15:53, 32.87s/it]

================================================================================
🧪 EXPERIMENTO 21
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  42%|████▏     | 21/50 [52:13<15:53, 32.87s/it]

✅ Experimento 21 concluído!
   Val Loss: 0.026844 | RMSE: 0.163842
[I 2026-02-10 01:23:39,439] Trial 21 finished with value: 0.16384185986298974 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  44%|████▍     | 22/50 [52:13<14:22, 30.80s/it]

================================================================================
🧪 EXPERIMENTO 22
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  44%|████▍     | 22/50 [52:45<14:22, 30.80s/it]

✅ Experimento 22 concluído!
   Val Loss: 0.026915 | RMSE: 0.164057
[I 2026-02-10 01:24:11,872] Trial 22 finished with value: 0.16405719793925722 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  46%|████▌     | 23/50 [52:45<14:05, 31.31s/it]

================================================================================
🧪 EXPERIMENTO 23
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  46%|████▌     | 23/50 [53:11<14:05, 31.31s/it]

✅ Experimento 23 concluído!
   Val Loss: 0.026844 | RMSE: 0.163842
[I 2026-02-10 01:24:38,035] Trial 23 finished with value: 0.16384185986298974 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  48%|████▊     | 24/50 [53:11<12:53, 29.75s/it]

================================================================================
🧪 EXPERIMENTO 24
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  48%|████▊     | 24/50 [53:43<12:53, 29.75s/it]

✅ Experimento 24 concluído!
   Val Loss: 0.026915 | RMSE: 0.164057
[I 2026-02-10 01:25:10,090] Trial 24 finished with value: 0.16405719793925722 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  50%|█████     | 25/50 [53:44<12:41, 30.45s/it]

================================================================================
🧪 EXPERIMENTO 25
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  50%|█████     | 25/50 [54:09<12:41, 30.45s/it]

✅ Experimento 25 concluído!
   Val Loss: 0.026844 | RMSE: 0.163842
[I 2026-02-10 01:25:35,606] Trial 25 finished with value: 0.16384185986298974 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  52%|█████▏    | 26/50 [54:09<11:35, 28.98s/it]

================================================================================
🧪 EXPERIMENTO 26
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 512
d_model: 64, heads: 8, layers: 2
LR: 0.0001, Batch: 64, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1279 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  52%|█████▏    | 26/50 [1:00:35<11:35, 28.98s/it]

✅ Experimento 26 concluído!
   Val Loss: 0.042684 | RMSE: 0.206601
[I 2026-02-10 01:32:01,994] Trial 26 finished with value: 0.20660129021309118 and parameters: {'features_idx': 3, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 8, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 1, 'learning_rate': 0.0001, 'batch_size': 64}. Best is trial 3 with value: 0.16365727266163665.

Best trial: 3. Best value: 0.163657:  54%|█████▍    | 27/50 [1:00:36<52:19, 136.51s/it]

================================================================================
🧪 EXPERIMENTO 27
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 3. Best value: 0.163657:  54%|█████▍    | 27/50 [1:01:09<52:19, 136.51s/it]

✅ Experimento 27 concluído!
   Val Loss: 0.026685 | RMSE: 0.163354
[I 2026-02-10 01:32:35,376] Trial 27 finished with value: 0.16335434441138605 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  56%|█████▌    | 28/50 [1:01:09<38:35, 105.25s/it]

================================================================================
🧪 EXPERIMENTO 28
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  56%|█████▌    | 28/50 [1:01:37<38:35, 105.25s/it]

✅ Experimento 28 concluído!
   Val Loss: 0.027301 | RMSE: 0.165230
[I 2026-02-10 01:33:04,042] Trial 28 finished with value: 0.1652298169149907 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  58%|█████▊    | 29/50 [1:01:37<28:47, 82.27s/it]

================================================================================
🧪 EXPERIMENTO 29
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  58%|█████▊    | 29/50 [1:01:57<28:47, 82.27s/it]

✅ Experimento 29 concluído!
   Val Loss: 0.027352 | RMSE: 0.165383
[I 2026-02-10 01:33:23,341] Trial 29 finished with value: 0.1653829186454626 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  60%|██████    | 30/50 [1:01:57<21:07, 63.38s/it]

================================================================================
🧪 EXPERIMENTO 30
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  60%|██████    | 30/50 [1:02:22<21:07, 63.38s/it]

✅ Experimento 30 concluído!
   Val Loss: 0.026857 | RMSE: 0.163880
[I 2026-02-10 01:33:48,848] Trial 30 finished with value: 0.16388025834124065 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  62%|██████▏   | 31/50 [1:02:22<16:28, 52.04s/it]

================================================================================
🧪 EXPERIMENTO 31
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  62%|██████▏   | 31/50 [1:02:54<16:28, 52.04s/it]

✅ Experimento 31 concluído!
   Val Loss: 0.026915 | RMSE: 0.164057
[I 2026-02-10 01:34:21,194] Trial 31 finished with value: 0.16405719793925722 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  64%|██████▍   | 32/50 [1:02:55<13:50, 46.11s/it]

================================================================================
🧪 EXPERIMENTO 32
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  64%|██████▍   | 32/50 [1:03:20<13:50, 46.11s/it]

✅ Experimento 32 concluído!
   Val Loss: 0.026844 | RMSE: 0.163842
[I 2026-02-10 01:34:46,956] Trial 32 finished with value: 0.16384185986298974 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  66%|██████▌   | 33/50 [1:03:20<11:20, 40.01s/it]

================================================================================
🧪 EXPERIMENTO 33
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  66%|██████▌   | 33/50 [1:03:53<11:20, 40.01s/it]

✅ Experimento 33 concluído!
   Val Loss: 0.026915 | RMSE: 0.164057
[I 2026-02-10 01:35:19,298] Trial 33 finished with value: 0.16405719793925722 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  68%|██████▊   | 34/50 [1:03:53<10:03, 37.71s/it]

================================================================================
🧪 EXPERIMENTO 34
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 512
d_model: 64, heads: 16, layers: 2
LR: 0.0001, Batch: 32, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1279 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  68%|██████▊   | 34/50 [1:34:05<10:03, 37.71s/it]

✅ Experimento 34 concluído!
   Val Loss: 0.038055 | RMSE: 0.195077
[I 2026-02-10 02:05:31,762] Trial 34 finished with value: 0.19507722989611428 and parameters: {'features_idx': 3, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 1, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  70%|███████   | 35/50 [1:34:06<2:22:37, 570.50s/it]

================================================================================
🧪 EXPERIMENTO 35
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 128, heads: 16, layers: 2
LR: 0.0001, Batch: 64, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  70%|███████   | 35/50 [1:34:25<2:22:37, 570.50s/it]

✅ Experimento 35 concluído!
   Val Loss: 0.028584 | RMSE: 0.169069
[I 2026-02-10 02:05:51,638] Trial 35 finished with value: 0.16906903538085616 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 64}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  72%|███████▏  | 36/50 [1:34:25<1:34:29, 404.96s/it]

================================================================================
🧪 EXPERIMENTO 36
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 512
d_model: 64, heads: 16, layers: 3
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1278 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  72%|███████▏  | 36/50 [1:34:48<1:34:29, 404.96s/it]

✅ Experimento 36 concluído!
   Val Loss: 0.029741 | RMSE: 0.172456
[I 2026-02-10 02:06:15,182] Trial 36 finished with value: 0.17245567374226645 and parameters: {'features_idx': 1, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  74%|███████▍  | 37/50 [1:34:49<1:02:56, 290.52s/it]

================================================================================
🧪 EXPERIMENTO 37
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 128, heads: 8, layers: 3
LR: 0.0001, Batch: 64, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  74%|███████▍  | 37/50 [1:44:23<1:02:56, 290.52s/it]

✅ Experimento 37 concluído!
   Val Loss: 0.031927 | RMSE: 0.178682
[I 2026-02-10 02:15:49,953] Trial 37 finished with value: 0.1786824813450219 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 8, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 1, 'learning_rate': 0.0001, 'batch_size': 64}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  76%|███████▌  | 38/50 [1:44:25<1:15:13, 376.15s/it]

================================================================================
🧪 EXPERIMENTO 38
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 2
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  76%|███████▌  | 38/50 [1:44:41<1:15:13, 376.15s/it]

✅ Experimento 38 concluído!
   Val Loss: 0.028341 | RMSE: 0.168347
[I 2026-02-10 02:16:07,964] Trial 38 finished with value: 0.16834677806203602 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  78%|███████▊  | 39/50 [1:44:41<49:11, 268.35s/it]

================================================================================
🧪 EXPERIMENTO 39
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 16, layers: 3
LR: 0.0005, Batch: 32, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  78%|███████▊  | 39/50 [1:50:57<49:11, 268.35s/it]

✅ Experimento 39 concluído!
   Val Loss: 0.036964 | RMSE: 0.192259
[I 2026-02-10 02:22:24,222] Trial 39 finished with value: 0.19225940522228596 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 1, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  80%|████████  | 40/50 [1:50:59<50:12, 301.27s/it]

================================================================================
🧪 EXPERIMENTO 40
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 512
d_model: 64, heads: 8, layers: 3
LR: 0.0001, Batch: 64, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1279 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  80%|████████  | 40/50 [1:51:25<50:12, 301.27s/it]

✅ Experimento 40 concluído!
   Val Loss: 0.035058 | RMSE: 0.187238
[I 2026-02-10 02:22:51,558] Trial 40 finished with value: 0.18723802344813575 and parameters: {'features_idx': 3, 'context_length': 512, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 8, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 64}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  82%|████████▏ | 41/50 [1:51:25<32:47, 218.56s/it]

================================================================================
🧪 EXPERIMENTO 41
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  82%|████████▏ | 41/50 [1:51:47<32:47, 218.56s/it]

✅ Experimento 41 concluído!
   Val Loss: 0.027785 | RMSE: 0.166687
[I 2026-02-10 02:23:13,933] Trial 41 finished with value: 0.1666873916515489 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 27 with value: 0.16335434441138605.

Best trial: 27. Best value: 0.163354:  84%|████████▍ | 42/50 [1:51:47<21:17, 159.70s/it]

================================================================================
🧪 EXPERIMENTO 42
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 27. Best value: 0.163354:  84%|████████▍ | 42/50 [1:52:20<21:17, 159.70s/it]

✅ Experimento 42 concluído!
   Val Loss: 0.026488 | RMSE: 0.162752
[I 2026-02-10 02:23:46,279] Trial 42 finished with value: 0.16275208960530635 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 42 with value: 0.16275208960530635.

Best trial: 42. Best value: 0.162752:  86%|████████▌ | 43/50 [1:52:20<14:10, 121.49s/it]

================================================================================
🧪 EXPERIMENTO 43
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 42. Best value: 0.162752:  86%|████████▌ | 43/50 [1:52:46<14:10, 121.49s/it]

✅ Experimento 43 concluído!
   Val Loss: 0.026844 | RMSE: 0.163842
[I 2026-02-10 02:24:12,675] Trial 43 finished with value: 0.16384185986298974 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 42 with value: 0.16275208960530635.

Best trial: 42. Best value: 0.162752:  88%|████████▊ | 44/50 [1:52:46<09:17, 92.97s/it]

================================================================================
🧪 EXPERIMENTO 44
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 42. Best value: 0.162752:  88%|████████▊ | 44/50 [1:53:20<09:17, 92.97s/it]

✅ Experimento 44 concluído!
   Val Loss: 0.026915 | RMSE: 0.164057
[I 2026-02-10 02:24:46,597] Trial 44 finished with value: 0.16405719793925722 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 42 with value: 0.16275208960530635.

Best trial: 42. Best value: 0.162752:  90%|█████████ | 45/50 [1:53:20<06:16, 75.25s/it]

================================================================================
🧪 EXPERIMENTO 45
================================================================================
Features: ['Vol_lag_1', 'Vol_lag_2', 'Vol_lag_3']
Context Length: 256
d_model: 64, heads: 16, layers: 3
LR: 0.0001, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1535 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 42. Best value: 0.162752:  90%|█████████ | 45/50 [1:53:48<06:16, 75.25s/it]

✅ Experimento 45 concluído!
   Val Loss: 0.026844 | RMSE: 0.163842
[I 2026-02-10 02:25:14,878] Trial 45 finished with value: 0.16384185986298974 and parameters: {'features_idx': 3, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 64, 'num_attention_heads': 16, 'num_hidden_layers': 3, 'ffn_dim': 512, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0001, 'batch_size': 32}. Best is trial 42 with value: 0.16275208960530635.

Best trial: 42. Best value: 0.162752:  92%|█████████▏| 46/50 [1:53:48<04:04, 61.17s/it]

================================================================================
🧪 EXPERIMENTO 46
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 42. Best value: 0.162752:  92%|█████████▏| 46/50 [1:54:15<04:04, 61.17s/it]

✅ Experimento 46 concluído!
   Val Loss: 0.025801 | RMSE: 0.160627
[I 2026-02-10 02:25:41,556] Trial 46 finished with value: 0.16062684237132324 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 46 with value: 0.16062684237132324.

Best trial: 46. Best value: 0.160627:  94%|█████████▍| 47/50 [1:54:15<02:32, 50.80s/it]

================================================================================
🧪 EXPERIMENTO 47
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 16, layers: 2
LR: 0.0005, Batch: 32, Patch: 1
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 46. Best value: 0.160627:  94%|█████████▍| 47/50 [2:01:02<02:32, 50.80s/it]

✅ Experimento 47 concluído!
   Val Loss: 0.033057 | RMSE: 0.181816
[I 2026-02-10 02:32:28,613] Trial 47 finished with value: 0.18181573978932586 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 16, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.2, 'patch_length': 1, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 46 with value: 0.16062684237132324.

Best trial: 46. Best value: 0.160627:  96%|█████████▌| 48/50 [2:01:03<05:16, 158.05s/it]

================================================================================
🧪 EXPERIMENTO 48
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 8, layers: 2
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 46. Best value: 0.160627:  96%|█████████▌| 48/50 [2:01:28<05:16, 158.05s/it]

✅ Experimento 48 concluído!
   Val Loss: 0.024366 | RMSE: 0.156096
[I 2026-02-10 02:32:54,824] Trial 48 finished with value: 0.15609563116137173 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 8, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 48 with value: 0.15609563116137173.

Best trial: 48. Best value: 0.156096:  98%|█████████▊| 49/50 [2:01:28<01:58, 118.13s/it]

================================================================================
🧪 EXPERIMENTO 49
================================================================================
Features: ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
Context Length: 256
d_model: 128, heads: 8, layers: 2
LR: 0.0005, Batch: 32, Patch: 16
================================================================================

Carregando dados de C:\Users\Lenovo\Documents\GitHub\iniciacao-cientifica\data\raw\BTCUSDT_5m.txt
Calculando features de volatilidade
Treino: 1534 amostras | Val: 256 | Teste: 512

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Best trial: 48. Best value: 0.156096:  98%|█████████▊| 49/50 [2:01:47<01:58, 118.13s/it]

✅ Experimento 49 concluído!
   Val Loss: 0.027034 | RMSE: 0.164420
[I 2026-02-10 02:33:14,118] Trial 49 finished with value: 0.164419721939663 and parameters: {'features_idx': 1, 'context_length': 256, 'forecast_horizon': 1, 'd_model': 128, 'num_attention_heads': 8, 'num_hidden_layers': 2, 'ffn_dim': 256, 'dropout': 0.1, 'patch_length': 16, 'learning_rate': 0.0005, 'batch_size': 32}. Best is trial 48 with value: 0.15609563116137173.

Best trial: 48. Best value: 0.156096: 100%|██████████| 50/50 [2:01:48<00:00, 146.16s/it]

================================================================================
✅ Busca Optuna concluída!
⏱️ Tempo total: 2:01:48.100061
🏆 Melhor RMSE: 0.156096
================================================================================

🏆 MELHORES HIPERPARÂMETROS (Optuna):
================================================================================
features_idx             : 1
context_length           : 256
forecast_horizon         : 1
d_model                  : 128
num_attention_heads      : 8
num_hidden_layers        : 2
ffn_dim                  : 256
dropout                  : 0.1
patch_length             : 16
learning_rate            : 0.0005
batch_size               : 32
================================================================================
⚠️ Não foi possível gerar visualizações Optuna: Tried to import 'plotly' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'plotly'.
   Instale: pip install plotly kaleido

In [38]:
import pandas as pd

optuna_results = pd.read_csv('optuna_results.csv')
optuna_results.sort_values(by='eval_loss', ascending=False).head()

experiment_id                                                        48
features               ['Vol_lag_1', 'Vol_week_mean', 'Vol_month_mean']
num_features                                                          3
context_length                                                      256
forecast_horizon                                                      1
d_model                                                             128
num_attention_heads                                                   8
num_hidden_layers                                                     2
ffn_dim                                                             256
dropout                                                             0.1
patch_length                                                         16
learning_rate                                                    0.0005
batch_size                                                           32
train_loss                                                     0.566512
eval_loss                                                      0.024366
eval_MSE                                                       0.024366
eval_MAE                                                       0.079874
eval_RMSE                                                      0.156096
eval_MAPE                                                     59.285718
epochs_trained                                                        0
status                                                          success
Name: 48, dtype: object